from bs4 import BeautifulSoup
import requests

seoul = requests.get('https://search.naver.com/search.naver?query=강남+날씨')
gyeon = requests.get('https://search.naver.com/search.naver?query=수원+날씨')
gangwon = requests.get('https://search.naver.com/search.naver?query=강원도+날씨')
chnam = requests.get('https://search.naver.com/search.naver?query=충청남도+날씨')
chbuk = requests.get('https://search.naver.com/search.naver?query=충청북도+날씨')
gynam = requests.get('https://search.naver.com/search.naver?query=경남+날씨')
gybuk = requests.get('https://search.naver.com/search.naver?query=경북+날씨')
junam = requests.get('https://search.naver.com/search.naver?query=전북+날씨')
jubuk = requests.get('https://search.naver.com/search.naver?query=전남+날씨')
jeju = requests.get('https://search.naver.com/search.naver?query=제주+날씨')
se_soup = BeautifulSoup(seoul.text, 'html.parser')
gy_soup = BeautifulSoup(gyeon.text, 'html.parser')
ga_soup = BeautifulSoup(gangwon.text, 'html.parser')
cn_soup = BeautifulSoup(chnam.text, 'html.parser')
cb_soup = BeautifulSoup(chbuk.text, 'html.parser')
gn_soup = BeautifulSoup(gynam.text, 'html.parser')
gb_soup = BeautifulSoup(gybuk.text, 'html.parser')
jn_soup = BeautifulSoup(junam.text, 'html.parser')
jb_soup = BeautifulSoup(jubuk.text, 'html.parser')
je_soup = BeautifulSoup(jeju.text, 'html.parser')

se_now = se_soup.find('div', {'class' : 'temperature_text'}).text.strip()
se_we = se_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
print(se_now + " " +se_we)
se_today = se_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(se_today)
se_tomorow = se_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(se_tomorow)

gy_now = gy_soup.find('div', {'class' : 'temperature_text'}).text.strip()
gy_we = gy_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
gy_today = gy_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
gy_tomorow = gy_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(gy_now + " " +gy_we)
print(gy_today)
print(gy_tomorow)

ga_now = ga_soup.find('div', {'class' : 'temperature_text'}).text.strip()
ga_we = ga_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
ga_today = ga_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
ga_tomorow = ga_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(ga_now + " " +ga_we)
print(ga_today)
print(ga_tomorow)

cn_now = cn_soup.find('div', {'class' : 'temperature_text'}).text.strip()
cn_we = cn_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
cn_today = cn_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
cn_tomorow = cn_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(cn_now + " " +cn_we)
print(cn_today)
print(cn_tomorow)

cb_now = cb_soup.find('div', {'class' : 'temperature_text'}).text.strip()
cb_we = cb_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
cb_today = cb_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
cb_tomorow = cb_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(cb_now + " " +cb_we)
print(cb_today)
print(cb_tomorow)

gn_now = gn_soup.find('div', {'class' : 'temperature_text'}).text.strip()
gn_we = gn_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
gn_today = gn_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
gn_tomorow = gn_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(gn_now + " " +gn_we)
print(gn_today)
print(gn_tomorow)

gb_now = gb_soup.find('div', {'class' : 'temperature_text'}).text.strip()
gb_we = gb_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
gb_today = gb_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
gb_tomorow = gb_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(gb_now + " " +gb_we)
print(gb_today)
print(gb_tomorow)

jn_now = jn_soup.find('div', {'class' : 'temperature_text'}).text.strip()
jn_we = jn_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
jn_today = jn_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
jn_tomorow = jn_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(jn_now + " " +jn_we)
print(jn_today)
print(jn_tomorow)

jb_now = jb_soup.find('div', {'class' : 'temperature_text'}).text.strip()
jb_we = jb_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
jb_today = jb_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
jb_tomorow = jb_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(jb_now + " " +jb_we)
print(jb_today)
print(jb_tomorow)

je_now = je_soup.find('div', {'class' : 'temperature_text'}).text.strip()
je_we = je_soup.find('span', {'class' : 'weather before_slash'}).text.strip()
je_today = je_soup.find('li', {'class': 'week_item today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
je_tomorow = je_soup.find('li', {'class': 'week_item holiday today'}).find('div', {'class':'day_data'}).find('div', {'class':'cell_temperature'}).text.strip()
print(je_now + " " +je_we)
print(je_today)
print(je_tomorow)